// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbqrxgpewqqenblrkebl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBicXJ4Z3Bld3FxZW5ibHJrZWJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NzcyOTMsImV4cCI6MjA2NDU1MzI5M30.nnUmVkU422xx97VGPB5MCwTvhpGRJ5IHkF6mtGb9d8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);